---
include:
# board: eyelash_sofle_left
# shield: nice_view

# Left (main) board
  - board: eyelash_sofle_left
    shield: nice_view_gem
    snippet: studio-rpc-usb-uart
    cmake-args: -DCONFIG_ZMK_STUDIO=y -DCONFIG_ZMK_STUDIO_LOCKING=n
    artifact-name: eyelash_sofle_studio_left
# Right board
  - board: eyelash_sofle_right
    shield: nice_view_gem
# Use this to reset pairing between boards
  - board: eyelash_sofle_left
    shield: settings_reset
